### ISSUE TITLE
any plan for GPU A100 and RDMA support? thanks

### ISSUE THREAD

**Issue by davinwei** [oracle-quickstart/oci-hpc-runbook-namd#2]

**Comment by lfeldman** [comment]
@glorialee820 could you please respond to @davinwei question?

**Comment by glorialee820** [comment]
Hi @davinwei,

Our next release will have GPU A100 with RDMA support. 

Best,
Gloria

**Comment by lfeldman** [comment]
It looks like @glorialee820 has answered. Closing the ticket.
